Assignments/Week6_Demo/Week6_Demo-war/src/java/cs544/cs/mum/edu/week6/entity/Car.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs544.cs.mum.edu.week6.entity;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * @author Enkhee
 */
@Entity
@Table(name = "CarTbl")
public class Car implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    private String Make;
    private String Model;
    @Column(name = "ManufacturingYear")
    private Integer Year;
    private Integer Miles;
    private Color Color;

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Car)) {
            return false;
        }
        Car other = (Car) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "cs544.cs.mum.edu.week6.entity.Car[ id=" + id + " ]";
    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the Make
     */
    public String getMake() {
        return Make;
    }

    /**
     * @param Make the Make to set
     */
    public void setMake(String Make) {
        this.Make = Make;
    }

    /**
     * @return the Model
     */
    public String getModel() {
        return Model;
    }

    /**
     * @param Model the Model to set
     */
    public void setModel(String Model) {
        this.Model = Model;
    }

    /**
     * @return the Year
     */
    public Integer getYear() {
        return Year;
    }

    /**
     * @param Year the Year to set
     */
    public void setYear(Integer Year) {
        this.Year = Year;
    }

    /**
     * @return the Miles
     */
    public Integer getMiles() {
        return Miles;
    }

    /**
     * @param Miles the Miles to set
     */
    public void setMiles(Integer Miles) {
        this.Miles = Miles;
    }

    /**
     * @return the Color
     */
    public Color getColor() {
        return Color;
    }

    /**
     * @param Color the Color to set
     */
    public void setColor(Color Color) {
        this.Color = Color;
    }

    public Car() {
    }

    public Car(String Make, String Model, int Year, int Miles, Color Color) {
        this.Make = Make;
        this.Model = Model;
        this.Year = Year;
        this.Miles = Miles;
        this.Color = Color;
    }
}

Assignments/Week6_Demo/Week6_Demo-war/src/java/cs544/cs/mum/edu/week6/entity/Color.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs544.cs.mum.edu.week6.entity;

/**
 *
 * @author Enkhee
 */
public enum Color {
    BLACK, WHITE, GREEN, BROWN, BLUE, YELLOW, ORANGE, RED;
}

Assignments/Week6_Demo/Week6_Demo-war/src/java/cs544/cs/mum/edu/week6/mb/CarMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs544.cs.mum.edu.week6.mb;

import cs544.cs.mum.edu.week6.entity.Car;
import cs544.cs.mum.edu.week6.service.CarService;
import cs544.cs.mum.edu.week6.service.CarServiceImpl;
import java.io.Serializable;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

/**
 *
 * @author Enkhee
 */
@Named(value = "carMB")
@RequestScoped
public class CarMB implements Serializable {

    @PersistenceContext(unitName = "Demo01_EntitiesPU")
    private EntityManager em;
    private Car car;
    private final CarService carService = new CarServiceImpl();
    private String message = null;

    /**
     * Creates a new instance of CarMB
     */
    public CarMB() {
        car = new Car();
    }

    public String show(Integer id) {
        car = carService.get(id);
        return "Car";
    }

    public String save() {
        em.persist(car);
        
//        if (car.getId() == null || car.getId() == 0) {
//            int generatedId = carService.create(car);
//            message = "New car had been successfully created. GeneratedId - " + generatedId;
//            car.setId(generatedId);
//        } else {
//            boolean result = carService.update(car.getId(), car);
//            message = "Result of update action is " + result;
//        }
//        System.out.println(message);
        return "Cars";
    }

    public Car getCar() {
        return car;
    }

    public void setCar(Car car) {
        this.car = car;
    }

}

Assignments/Week6_Demo/Week6_Demo-war/src/java/cs544/cs/mum/edu/week6/mb/CarsMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs544.cs.mum.edu.week6.mb;

import cs544.cs.mum.edu.week6.entity.Car;
import cs544.cs.mum.edu.week6.service.CarService;
import cs544.cs.mum.edu.week6.service.CarServiceImpl;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

/**
 *
 * @author Enkhee
 */
@Named(value = "carsMB")
@RequestScoped
public class CarsMB implements Serializable {

    @PersistenceContext(unitName = "Demo01_EntitiesPU")
    private EntityManager em;
    private List<Car> cars;
    private final CarService carService = new CarServiceImpl();

    public CarsMB() {
        cars = carService.getList();
    }

    public List<Car> getCars() {
        return cars;
    }

    public void setCars(List<Car> cars) {
        this.cars = cars;
    }

    public void deleteCar(Integer id) {
        carService.delete(id);
        cars = carService.getList();
    }

}

Assignments/Week6_Demo/Week6_Demo-war/web/Car.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Week6 - Car</title>
    </h:head>
    <h:body>
        <h1>Car information</h1>
        <h:form>
            <h:inputHidden value="#{carMB.car.id}" />
            <h:panelGrid columns="2">

                <h:outputText value ="ID:"/>
                <h:inputText value="#{carMB.car.id}" disabled="true" />

                <h:outputText value ="Make : "/>
                <h:inputText value="#{carMB.car.make}" />

                <h:outputText value ="Model : "/>
                <h:inputText value="#{carMB.car.model}" />

                <h:outputText value ="Miles : "/>
                <h:inputText value="#{carMB.car.miles}" />

                <h:outputText value ="Manufacturing Year : "/>
                <h:inputText value="#{carMB.car.year}" />

                <h:outputText value ="Color : "/>
                <h:inputText value="#{carMB.car.color}" />
            </h:panelGrid>
            <h:commandButton value="Back" action="Cars?faces-redirect=true" />
            <h:commandButton value="Save" action="#{carMB.save()}"/>
        </h:form>
    </h:body>
</html>

Assignments/Week6_Demo/Week6_Demo-war/web/Cars.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Week6 - Cars</title>
    </h:head>
    <h:body>
        <dir>
            <h1>Car list</h1>
        </dir>
        <h:form>
            <h:dataTable value="#{carsMB.cars}" var="carItem">
                <f:facet name="header">
                    <tr>
                        <td>ID</td>
                        <td>MAKE</td>
                        <td>MODEL</td>
                        <td>MILES</td>
                        <td>MANU/YEAR</td>
                        <td>COLOR</td>
                    </tr>
                </f:facet>
                <h:column>
                    #{carItem.id}
                </h:column>
                <h:column>
                    #{carItem.make}
                </h:column>
                <h:column>
                    #{carItem.model}
                </h:column>
                <h:column>
                    #{carItem.miles}
                </h:column>
                <h:column>
                    #{carItem.year}
                </h:column>
                <h:column>
                    #{carItem.color}
                </h:column>
                <h:column>
                    <h:commandButton value="Update" action="#{carMB.show(carItem.id)}" />
                </h:column>
                <h:column>
                    <h:commandButton value="Delete" action="#{carsMB.deleteCar(carItem.id)}" />
                </h:column>
            </h:dataTable>
            <h:commandButton value="Create" action="Car?faces-redirect=true"/>
        </h:form>
    </h:body>
</html>

Assignments/Week6_Demo/Week6_Demo-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>JSF page</title>
    </h:head>
    <h:body>
        Hello from Facelets<br/>test
    </h:body>
</html>