Assignments/Week10/Week10-war/src/java/cs544/cs/mum/edu/week10/entity/Car.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs544.cs.mum.edu.week10.entity;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PostUpdate;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.TypedQuery;
import javax.persistence.Version;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

/**
 *
 * @author Enkhee
 */
@Entity
@Table(name = "Week10_Car")
public class Car {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    private String make;
    private String model;
    @Column(name = "ManufacturingYear")
    private Integer year;
    private Integer miles;
    @Enumerated(EnumType.STRING)
    private Color color;

    @Column(name = "version_num")
    @Version
    private Integer version;

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Car() {
    }

    public String getMake() {
        return make;
    }

    public void setMake(String Make) {
        this.make = Make;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String Model) {
        this.model = Model;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer Year) {
        this.year = Year;
    }

    public Integer getMiles() {
        return miles;
    }

    public void setMiles(Integer Miles) {
        this.miles = Miles;
    }

    public Color getColor() {
        return color;
    }

    public void setColor(Color Color) {
        this.color = Color;
    }

    @Override
    public String toString() {
        return "Car{" + "id=" + id + ", make=" + make + ", model=" + model + ", year=" + year + ", miles=" + miles + ", color=" + color + ", version=" + version + '}';
    }

    
    public static List<Car> getAllCars(EntityManager em) {
        List<Car> cars = null;
        CriteriaBuilder builder = em.getCriteriaBuilder();
        CriteriaQuery<Car> cquery = builder.createQuery(Car.class);
        Root<Car> root = cquery.from(Car.class);
        cquery.select(root);
        TypedQuery<Car> query = em.createQuery(cquery);

        cars = query.getResultList();
        return cars;
    }
    
//    @PrePersist
    private void prePrintId(){
        printId("PrePersist");
    }

//    @PostPersist
    private void postPrintId(){
        printId("PostPersist");
    }
    
    @PreUpdate
    private void preUpdateId(){
        printId("PreUpdate");
    }
    
    @PostUpdate
    private void postUpdateId(){
        printId("PostUpdate");
    }
    
    private void printId(String str){
        System.out.println("callback ID from " + str + " : " + this.toString());
    }
 }

Assignments/Week10/Week10-war/src/java/cs544/cs/mum/edu/week10/entity/Color.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs544.cs.mum.edu.week10.entity;

/**
 *
 * @author Enkhee
 */
public enum Color {
    BLACK, WHITE, GREEN, BROWN, BLUE, YELLOW, ORANGE, RED;
}

Assignments/Week10/Week10-war/src/java/cs544/cs/mum/edu/week10/mb/CarMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs544.cs.mum.edu.week10.mb;

import cs544.cs.mum.edu.week10.entity.Car;
import java.io.Serializable;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.Transactional;

/**
 *
 * @author Enkhee
 */
@Named
//@RequestScoped
@SessionScoped
public class CarMB implements Serializable {

    @PersistenceContext(unitName = "Week10-warPU")
    private EntityManager em;
    private Car car;

    public Car getCar() {
        return this.car;
    }

    public void setCar(Car car) {
        this.car = car;
    }

    /**
     * Creates a new instance of CarMB
     */
    public CarMB() {
    }

    public String create(){
        car = new Car();
        return "car";
    }
    
    @Transactional
    public String save() {
        car = em.merge(car);
//        em.persist(car);
        return "index";
    }

    @Transactional
    public String update(Car carIn) {
        car = em.find(Car.class, carIn.getId());
        return "car";
    }
}

Assignments/Week10/Week10-war/src/java/cs544/cs/mum/edu/week10/mb/CarsMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs544.cs.mum.edu.week10.mb;

import cs544.cs.mum.edu.week10.entity.Car;
import java.util.List;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.Transactional;

/**
 *
 * @author Enkhee
 */
@Named
@RequestScoped
public class CarsMB {

    @PersistenceContext(unitName = "Week10-warPU")
    private EntityManager em;
    private Car car;
    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Car getCar() {
        return car;
    }

    public void setCar(Car car) {
        this.car = car;
    }
    /**
     * Creates a new instance of CarsMB
     */
    public CarsMB() {
    }
    
    public List<Car> getCars(){
        return Car.getAllCars(em);
    }
    
    public int getCarsCount(){
        return Car.getAllCars(em).size();
    }
    
//    @Transactional
    public String deletePage(Car carItem) {
        car = em.find(Car.class, carItem.getId());
        id = car.getId();
        System.out.println("id: " + car.getId());
        return "delete";
    }
    
    @Transactional
    public String delete() {
        System.out.println("dd: " + id);
        car = em.find(Car.class, id);
        em.remove(car);
        return "index";
    }
}

Assignments/Week10/Week10-war/web/car.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Car</title>
    </h:head>
    <h:body>
        Car<br/>
        <h:form>
            <h:panelGrid columns="2">
                <h:outputText value ="Make : "/>
                <h:inputText value="#{carMB.car.make}" />

                <h:outputText value ="Model : "/>
                <h:inputText value="#{carMB.car.model}" />

                <h:outputText value ="Miles : "/>
                <h:inputText value="#{carMB.car.miles}" />

                <h:outputText value ="Manufacturing Year : "/>
                <h:inputText value="#{carMB.car.year}" />

                <h:outputText value ="Color : "/>
                <h:inputText value="#{carMB.car.color}" />
            </h:panelGrid>
            <h:commandButton value="Back" action="index" />
            <h:commandButton value="Save" action="#{carMB.save()}" />
        </h:form>
    </h:body>
</html>

Assignments/Week10/Week10-war/web/delete.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Car</title>
    </h:head>
    <h:body>
        <h:form>
        Cars count:#{carsMB.carsCount} <br/>
            <h:panelGrid columns="2">
                <h:inputHidden value="#{carsMB.id}" />
                <h:outputText value ="ID : "/> #{carsMB.car.id}
                <h:outputText value ="Make : "/> #{carsMB.car.make}

                <h:outputText value ="Model : "/>#{carsMB.car.model}

                <h:outputText value ="Miles : "/>#{carsMB.car.miles}

                <h:outputText value ="Manufacturing Year : "/>#{carsMB.car.year}

                <h:outputText value ="Color : "/>#{carsMB.car.color}
                
            </h:panelGrid>
            <h:commandButton value="Back" action="index" />
            <h:commandButton value="delete" action="#{carsMB.delete()}" />
        </h:form>
    </h:body>
</html>

Assignments/Week10/Week10-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Week 10</title>
    </h:head>
    <h:body>
        Cars (#{carsMB.carsCount})
        <h:form>
            <h:commandButton value="Create Car" action="#{carMB.create()}"/><br/>
            
            <h:dataTable value="#{carsMB.cars}" var="carItem">                
                <f:facet name="header">
                    <tr>
                        <td>ID</td>
                        <td>MAKE</td>
                        <td>MODEL</td>
                        <td>MILES</td>
                        <td>MANU/YEAR</td>
                        <td>COLOR</td>
                    </tr>
                </f:facet>
                <h:column>
                    #{carItem.id}
                </h:column>
                <h:column>
                    #{carItem.make}
                </h:column>
                <h:column>
                    #{carItem.model}
                </h:column>
                <h:column>
                    #{carItem.miles}
                </h:column>
                <h:column>
                    #{carItem.year}
                </h:column>
                <h:column>
                    #{carItem.color}
                </h:column>
                <h:column>
                    <h:commandButton value="Update" action="#{carMB.update(carItem)}" />
                </h:column>
                <h:column>
                    <h:commandButton value="Delete" action="#{carsMB.deletePage(carItem)}" />
                </h:column>
            </h:dataTable>
        </h:form>
    </h:body>
</html>