Assignments/Week12/Week12-war/src/java/cs544/cs/mum/edu/week12/mb/CustomerMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs544.cs.mum.edu.week12.mb;

import cs544.cs.mum.edu.week12.entity.Customer;
import cs544.cs.mum.edu.week12.stateless.CustomerBean;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 *
 * @author Enkhee
 */
@Named
@SessionScoped
public class CustomerMB implements Serializable {
    
    private Customer customer;
    @EJB
    private CustomerBean customerBean;

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public CustomerMB() {
    }
    
    public String create(){
        customer = new Customer();
        return "customer";
    }
    
    public String save() {
        customerBean.updateCustomer(customer);
        return "index";
    }

    public String update(Customer customerIn) {
        customer = customerBean.getCustomer(customerIn.getId());
        return "customer";
    }

    public String delete(Customer customerIn) {
        customer = customerBean.getCustomer(customerIn.getId());
        customerBean.deleteCustomer(customerIn);
        return "index";
    }
}

Assignments/Week12/Week12-war/src/java/cs544/cs/mum/edu/week12/mb/CustomersMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs544.cs.mum.edu.week12.mb;

import cs544.cs.mum.edu.week12.entity.Customer;
import cs544.cs.mum.edu.week12.stateless.CustomerBean;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 *
 * @author Enkhee
 */
@Named
@SessionScoped
public class CustomersMB implements Serializable {

    @EJB
    private CustomerBean customerBean;

    public CustomersMB() {
    }

//    @Interceptors(LoggingInterceptor.class)
    public List<Customer> getCustomers() {
        return customerBean.getCustomers();
    }

}

Assignments/Week12/Week12-war/web/customer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Customer</title>
    </h:head>
    <h:body>
        Customer<br/>
        <h:form>
            <h:panelGrid columns="2">
                <h:outputText value ="First name : "/>
                <h:inputText value="#{customerMB.customer.firstName}" />

                <h:outputText value ="Last name : "/>
                <h:inputText value="#{customerMB.customer.lastName}" />

                <h:outputText value ="Age : "/>
                <h:inputText value="#{customerMB.customer.age}" />

            </h:panelGrid>
            <h:commandButton value="Back" action="index" />
            <h:commandButton value="Save" action="#{customerMB.save()}" />
        </h:form>
    </h:body>
</html>

Assignments/Week12/Week12-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Week 12</title>
    </h:head>
    <h:body>
        Customers
        <h:form>
            <h:commandButton value="Create Customer" action="#{customerMB.create()}"/><br/>
            
            <h:dataTable value="#{customersMB.customers}" var="customerItem">                
                <f:facet name="header">
                    <tr>
                        <td>ID</td>
                        <td>first name</td>
                        <td>last name</td>
                        <td>age</td>
                    </tr>
                </f:facet>
                <h:column>
                    #{customerItem.id}
                </h:column>
                <h:column>
                    #{customerItem.firstName}
                </h:column>
                <h:column>
                    #{customerItem.lastName}
                </h:column>
                <h:column>
                    #{customerItem.age}
                </h:column>
                <h:column>
                    <h:commandButton value="Update" action="#{customerMB.update(customerItem)}" />
                </h:column>
                <h:column>
                    <h:commandButton value="Delete" action="#{customerMB.delete(customerItem)}" />
                </h:column>
            </h:dataTable>
        </h:form>
    </h:body>
</html>